<?php

/**
 * Implements hook_cron().
 */
function cron_examples_cron() {
  // Do something.
}

/**
 * Implements hook_cronapi().
 */
function cron_example_cronapi() {
  return array(
    'cron_example_cronjob' => array(
      'title' => 'Cron api example',
      'scheduler' => array(
        'name' => 'crontab',
        'crontab' => array(
          'rules' => array('* * * * *'),
        ),
      ),
    )
  );
}

function cron_example_cronjob($op, $job = NULL) {
  batch_set(array(
    'operations' => array(
      array('cron_example_cronjob_operation', array()),
    ),
  ));

  $batch =& batch_get();
  $batch['progressive'] = FALSE;
  batch_process();
}

function cron_example_cronjob_operation() {
  sleep(1);
}